### ISSUE TITLE
Cannot create project

### ISSUE THREAD

**Issue by nesteruk** [stack72/TeamCitySharp#54]
JsonFx.Serialization.SerializationException was unhandled
  HResult=-2146233079
  Message=The encoding requested does not have a corresponding decoder
  Source=EasyHttp
  StackTrace:
       at EasyHttp.Codecs.DefaultDecoder.ObtainDeserializer(String contentType) in d:\BuildAgent-02\work\f438280827ed948a\src\EasyHttp\Codecs\DefaultDecoder.cs:line 44
       at EasyHttp.Codecs.DefaultDecoder.DecodeToStatic[T](String input, String contentType) in d:\BuildAgent-02\work\f438280827ed948a\src\EasyHttp\Codecs\DefaultDecoder.cs:line 22
       at EasyHttp.Http.HttpResponse.StaticBody[T](String overrideContentType) in d:\BuildAgent-02\work\f438280827ed948a\src\EasyHttp\Http\HttpResponse.cs:line 111
       at TeamCitySharp.Connection.TeamCityCaller.Post[T](String data, String urlPart)
       at TeamCitySharp.TeamCityClient.CreateProject(String projectName)
       at TeamCityDistributedSln.Program.Main(String[] args) in c:\Dropbox\Projects\Wild\TeamCityDistributedSln\TeamCityDistributedSln\Program.cs:line 17
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by satyaprakashv** [comment]
Hey stack72,

I am using TC 10 and using this to automate the TC Project creation and creating build configurations and Build Steps from my automation tool. I need some urgent help.

I am also getting the same error while creating Build steps using. (FYI Build Step is getting created in TC and then after it is throwing the error)

public void PostRawBuildStep(BuildTypeLocator locator, string rawXml)

My XML is here below.
<step id="RUNNER_11" name="Copy Sitecore License file" type="simpleRunner">
<properties count="3">
<property name="script.content" value="(Robocopy c:\SitecoreLibraries %system.teamcity.build.checkoutDir%\lib /E) ^ exit 0" />
<property name="teamcity.step.mode" value="default" />
<property name="use.custom.script" value="true" />
</properties>
</step>

Error:
The encoding requested does not have a corresponding decoder

   at EasyHttp.Codecs.DefaultDecoder.ObtainDeserializer(String contentType)
   at EasyHttp.Codecs.DefaultDecoder.DecodeToStatic[T](String input, String contentType)
   at EasyHttp.Http.HttpResponse.StaticBody[T](String overrideContentType)
   at TeamCityHelper.Connection.TeamCityCaller.Post[T](String data, String contenttype, String urlPart, String accept) in C:\work\CodeBase\GIT\TeamCityAutomation\src\TeamCitySharp\Connection\TeamCityCaller.cs:line 149
   at TeamCityHelper.Connection.TeamCityCaller.PostFormat[T](Object data, String contenttype, String accept, String urlPart, Object[] parts) in C:\work\CodeBase\GIT\TeamCityAutomation\src\TeamCitySharp\Connection\TeamCityCaller.cs:line 45
   at TeamCityHelper.ActionTypes.BuildConfigs.PostRawBuildStep(BuildTypeLocator locator, String rawXml) in C:\work\CodeBase\GIT\TeamCityAutomation\src\TeamCitySharp\ActionTypes\BuildConfigs.cs:line 109
   at DevOpsAutomation.TeamCityUI.btnCreateProject_Click(Object sender, EventArgs e)

**Comment by mavezeau** [comment]
Hi satyaprakashv
The main maintener of this project didn't support this project since many year, I recommend to use my fork and the current version was not supported teamcity 10.  

In the same time, it's possible to use directly the latest version from the nuget.org

Link to nuget.org: [https://www.nuget.org/packages/TeamCitySharp-forked-mavezeau/](https://www.nuget.org/packages/TeamCitySharp-forked-mavezeau/)
Link to github: [https://github.com/mavezeau/TeamCitySharp](https://github.com/mavezeau/TeamCitySharp)

Regards!
Marc-Andre Vezeau

**Comment by satyaprakashv** [comment]
Awesome .. Thanks a lot Marc..
Seems there are more new methods available now. Hope all will support my requirements..

Thanks
Satya

**Comment by mavezeau** [comment]
Yes, I added many new features if you missing some stocks just contact me on my fork  :)

**Comment by satyaprakashv** [comment]
Hey mavezeau,
I could not see to create an issue/comment on your fork page:
I am getting the same error as above..

my XML for create anew build step is as below:
<step id="RUNNER_11" name="Copy Sitecore License file" type="simpleRunner"><properties count="3"><property name="script.content" value="(Robocopy c:\SitecoreLibraries %system.teamcity.build.checkoutDir%\lib /E) ^ exit 0" /><property name="teamcity.step.mode" value="default" /><property name="use.custom.script" value="true" /></properties></step>

**Comment by mavezeau** [comment]
I dont see your xml but I send a little version of code...  In the same time, I found an issue in the code ... I already fixed the bug and I regenerate a new version.

We need to wait that nuget approved the package , but it's already available 
https://www.nuget.org/packages/TeamCitySharp-forked-mavezeau/1.0.56

E.g. of the code to create a new project, new build config and build step 
`var server = "server";
var username = "admin";
var password = "admin";
var m_teamCityClient = new TeamCityClient(server);

m_teamCityClient.Connect(username, password);
var p = m_teamCityClient.Projects.Create("NewProject", "TeamcityDashboardScenario");
var bt = m_teamCityClient.BuildConfigs.CreateConfigurationByProjectId(p.Id, "testNewConfig");
var xml = "< step type=\"simpleRunner\">" +
                    "< properties>" +
                      "< property name=\"script.content\" value=\"@echo off&#xA;echo Step1&#xA;touch step1.txt\" />" +
                      "< property name=\"teamcity.step.mode\" value=\"default\" />" +
                      "< property name=\"use.custom.script\" value=\"true\" />" +
                    "< /properties>" +
                  "<  /step>";
m_teamCityClient.BuildConfigs.PostRawBuildStep(BuildTypeLocator.WithId(bt.Id),xml );`

PS :I added a space before each tag ex "< step" because the editor does not display the tag...
Regards,
Marc-André

**Comment by satyaprakashv** [comment]
Hey Mark,
I found one more issue while creating VCS-Roots..
I Used  method my code look like this below:

   VcsRoot vcsroot = new VcsRoot();
                vcsroot.Id = project.Name + "_vcsroot1_01";
                vcsroot.Name = project.Name + "_vcsroot1";
                vcsroot.VcsName = "jetbrains.git";

                TeamCityWrapper.DomainEntities.Properties properties= new TeamCityWrapper.DomainEntities.Properties();
                properties.Add("agentCleanFilesPolicy", "ALL_UNTRACKED");
                vcsroot.Properties = properties;

client.VcsRoots.SetVcsRootValue(vcsroot, VcsRootValue.ProjectId, project.Id);

Error:
Forbidden Error: Forbidden
HTTP: Forbidden
URL: http://localhost:90/httpAuthTest33_vcsroot1_01
<html><head><title>Apache Tomcat/7.0.68 - Error report</title><style></style> </head><body><h1>HTTP Status 403 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.68</h3></body></html>

Stack Track:
   at TeamCityWrapper.Connection.TeamCityCaller.ThrowIfHttpError(HttpResponse response, String url) in C:\work\CodeBase\GIT\TeamCityAutomation\src\TeamCityWrapper\Connection\TeamCityCaller.cs:line 238
   at TeamCityWrapper.Connection.TeamCityCaller.MakePutRequest(Object data, String contenttype, String urlPart, String accept) in C:\work\CodeBase\GIT\TeamCityAutomation\src\TeamCityWrapper\Connection\TeamCityCaller.cs:line 216
   at TeamCityWrapper.Connection.TeamCityCaller.Put(Object data, String contenttype, String urlPart, String accept) in C:\work\CodeBase\GIT\TeamCityAutomation\src\TeamCityWrapper\Connection\TeamCityCaller.cs:line 178
   at TeamCityWrapper.Connection.TeamCityCaller.PutFormat(Object data, String contenttype, String urlPart, Object[] parts) in C:\work\CodeBase\GIT\TeamCityAutomation\src\TeamCityWrapper\Connection\TeamCityCaller.cs:line 66
   at TeamCityWrapper.ActionTypes.VcsRoots.SetVcsRootValue(VcsRoot vcsRoot, VcsRootValue field, Object value) in C:\work\CodeBase\GIT\TeamCityAutomation\src\TeamCityWrapper\ActionTypes\VcsRoots.cs:line 56
   at DevOpsAutomation.TeamCityUI.btnCreateProject_Click(Object sender, EventArgs e) in C:\work\CodeBase\GIT\TeamCityAutomation\DevOpsAutomation\TeamCityUI.cs:line 231

**Comment by mavezeau** [comment]
Hi Satya,

I made a little refactoring to fix your issue. 

I created new methods :  
for VcsRoot:
- VcsRoot CreateVcsRoot(VcsRoot configurationName, string projectId);
- void SetConfigurationProperties(VcsRoot vcsRootId, string key, string value);
- void DeleteProperties(VcsRoot vcsRootId, string parameterName);
- void DeleteVcsRoot(VcsRoot vcsRoot);

And I modified 
for VcsRoot: 
- (Fix) void SetVcsRootValue(VcsRoot vcsRoot, VcsRootValue field, object value)

How to use the new stuff: 

`

      var project = m_client.Projects.ById("Test");
      var vcsroot = new VcsRoot
      {
        Id = project.Id + "_vcsroot1_01",
        Name = project.Name + "_vcsroot1",
        VcsName = "jetbrains.git",
        Project = new Project {Id = project.Id}
      };

      var properties = new Properties();

      properties.Add("agentCleanFilesPolicy", "IGNORED_ONLY");
      vcsroot.Properties = properties;

      var vcsroot2 = m_client.VcsRoots.CreateVcsRoot(vcsroot, project.Id);
     
      m_client.VcsRoots.SetVcsRootValue(vcsroot2, VcsRootValue.Name, "TestChangeName");

      m_client.VcsRoots.SetConfigurationProperties(vcsroot2, "agentCleanFilesPolicy", "ALL_UNTRACKED");
      m_client.VcsRoots.SetConfigurationProperties(vcsroot2, "tt", "tt2");
      m_client.VcsRoots.DeleteProperties(vcsroot2,"tt");
      m_client.VcsRoots.DeleteVcsRoot(vcsroot2);
`

The new version was already avalaible.

Regards,

**Comment by satyaprakashv** [comment]
Hey Marc,

Is there any API method to set Sonar Qube server properties. see this below, I have installed a plugin and that show as a TAB in TeamCity,I have added all properties manually, but how can I configure all these properties using the TC API?

![image](https://user-images.githubusercontent.com/36186321/37945403-b02151e2-319d-11e8-8364-2c87c44a9286.png)

Thanks and Regards
Satya

**Comment by satyaprakashv** [comment]
Hi Mavezeau,

Reference to the above post I have created one method to post raw XML for creating a ProjectFeature for setting up SonarQube Server Profile using the Rest API - 

http://<teamcity.domain.name>/app/rest/projects/<Project Name>/projectFeatures

When we POST the below XML (consisting of SonarQube Server Profile settings)  to REST API, it gives an error that the type parameter cannot be empty (Attribute of projectFeature element). 
However, when I provide a random type (say "sonar-plugin")  the project extension gets added to - C:\ProgramData\JetBrains\TeamCity\config\projects\<projectName>\project-config.xml but the SonarQuebe Server profile does not created and is not visible under SonarQube Server. Refer the screeshot below
The crux of the issue is that the SonarQube Server profile is detected as a legitimate ProjectFeature only when the type parameter is left Empty. But irony of the API is that it does not allow to post the XML with an empty type attribute. 
Any help in the issue or pointer to work around would be greatly appreciated. Thanks in advance !
<projectFeature id="PROJECT_EXT_1" type="sonar-plugin" href="/app/rest/projects/id:HabitatDev/projectFeatures/id:PROJECT_EXT_1">
<properties count="8" href="/app/rest/projects/id:HabitatDev/projectFeatures/id:PROJECT_EXT_1/properties">
<property name="id" value="626e084f-842e-44db-9ebe-27c094bc2350"/>
<property name="jdbcPassword" value="zxx5dd5352e88ac71fe"/>
<property name="jdbcUrl" value="http://buildservervm.westus2.cloudapp.azure.com:9092/"/>
<property name="jdbcUsername" value="sonar"/>
<property name="login" value="admin"/>
<property name="name" value="CI Sonar Instance-TEST"/>
<property name="password" value="zxx0feb335798e7f083"/>
<property name="url" value="http://buildservervm.westus2.cloudapp.azure.com:9000"/>
</properties>
</projectFeature>

**Comment by mavezeau** [comment]
Hi Satya,
Sorry for the delay. I didn`t see your previous message. 

I never try SonarQube with Teamcity, I don`t know if it is an issue with sonar, the rest 
 api or your sonar teamcity  plugin ...  
Normally, this rest wrapper didn`t validate or modify the xml sent, for this reason I think it`s more and issue with  the sonar plugin. 

But I will check soon in my side. I don`t know if I will have time this week to check this. 

At the same time, is It possible to configure your server manually and just assign this projectFeature on your project ?

**Comment by satyaprakashv** [comment]
Hi Mavezeau,
Thanks for your prompt response...
I am able to create project feature by posting the XML, real issue is 
**_type_** parameter cannot be empty (Attribute of projectFeature element) while calling the API.

projectFeature id="PROJECT_EXT_1" type="**_sonar-plugin_**" 
However, when I provide a type (say "sonar-plugin") the project extension gets added into TC but that will actualy not visible in TC Project Settings. other wise it is visible. I feeling that is TC issue. I have posted a issue there and waiting for any response.

I thought if I could get some help from you.

Regards
Satya

**Comment by mavezeau** [comment]
Hi Satya, 

I added the capability to create and delete a new Project Feature on the latest version 1.0.59. 
https://www.nuget.org/packages/TeamCitySharp-forked-mavezeau/1.0.59

On Project: 
ProjectFeatures GetProjectFeatures(string projectLocatorId);
ProjectFeature GetProjectFeatureByProjectFeature(string projectLocatorId, string projectFeatureId);
ProjectFeature CreateProjectFeature(string projectId, ProjectFeature projectFeature);
void DeleteProjectFeature(string projectId, string projectFeatureId);

Just check if it's working with the new stuff...
Regards
